{% set name = "napari-blossom" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4786d7f10e6d61e78bc76e85f1f8af20aeaaa03812afdb7cca726e8fdfd2bc28
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - focal-loss >=0.0.7
    - magicgui >=0.6.1
    - napari
    - numpy >=1.23.0
    - opencv >=4.7.0.68
    - pillow >=9.3.0
    - python >=3.8
    - qtpy
    - scikit-image >=0.19.3
    - tensorflow >=2.11.0
    - tqdm >=4.64.1

test:
  imports:
    - napari_blossom
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-blossom
  summary: Segmentation of blossom apple tree images
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/hereariim/napari-blossom

extra:
  recipe-maintainers:
    - goanpeca
    - hereariim
    - jaimergp
