{% set name = "napari-blossom" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-blossom-{{ version }}.tar.gz
  sha256: c3b377691a18c75e85f0927e36c2a18b2bf1e0d45fed5f232b90f2a0d5b49148
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - focal-loss >=0.0.7
    - magicgui >=0.6.1
    - napari
    - numpy >=1.23.0
    - opencv >=4.7.0.68
    - pillow >=9.3.0
    - python >={{ python_min }}
    - qtpy
    - scikit-image >=0.19.3
    - tensorflow >=2.11.0
    - tqdm >=4.64.1

test:
  imports:
    - napari_blossom
  commands:
    - pip list
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-blossom
  summary: Segmentation of blossom apple tree images
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/hereariim/napari-blossom

extra:
  recipe-maintainers:
    - goanpeca
    - hereariim
    - jaimergp
